<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-201805291825" ignored="0" name="Test" tests="7" failures="3" timestamp="02 十一月 2018 15:37:58 GMT" time="4.719" errors="0">
  <testcase name="testRegist" time="0.293" classname="com.qa.tests.RegistTest">
    <failure type="java.lang.AssertionError" message="code is not ok expected [CodeOk] but found [2]">
      <![CDATA[java.lang.AssertionError: code is not ok expected [CodeOk] but found [2]
at com.qa.tests.RegistTest.testRegist(RegistTest.java:55)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRegist -->
  <testcase name="testRegist" time="0.017" classname="com.qa.tests.RegistTest">
    <failure type="java.lang.AssertionError" message="code is not ok expected [CodeOk] but found [2]">
      <![CDATA[java.lang.AssertionError: code is not ok expected [CodeOk] but found [2]
at com.qa.tests.RegistTest.testRegist(RegistTest.java:55)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRegist -->
  <testcase name="testRegist" time="0.019" classname="com.qa.tests.RegistTest">
    <failure type="java.lang.AssertionError" message="code is not ok expected [CodeOk] but found [2]">
      <![CDATA[java.lang.AssertionError: code is not ok expected [CodeOk] but found [2]
at com.qa.tests.RegistTest.testRegist(RegistTest.java:55)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testRegist -->
  <testcase name="putTest" time="0.708" classname="com.qa.tests.PutApiTest"/>
  <testcase name="testPostAPI" time="0.605" classname="com.qa.tests.PostApiTest"/>
  <testcase name="testGetAPI" time="0.822" classname="com.qa.tests.GetApiTest"/>
  <testcase name="deleteApiTest" time="1.966" classname="com.qa.tests.DeleteApiTest"/>
</testsuite> <!-- Test -->
